CHAT RUN

  The `ai chat run` command initiates bulk processing of inputs thru an
  AI language model (e.g. OpenAI's GPT4) and/or a python function.

USAGE: ai chat run [...]

  CONNECTION                            (see: ai help connection)
    --deployment DEPLOYMENT             (see: ai help chat deployment)
    --endpoint ENDPOINT                 (see: ai help chat endpoint)
    --key KEY                           (see: ai help chat key)

  INPUT                                 (see: ai help chat run input)
    --input-data FILE                   (see: ai help chat run input data)
    --input-data-mapping MAPPINGs       (see: ai help chat run input data mapping)
    --system PROMPT                     (see: ai help chat system prompt)
    --user MESSAGE                      (see: ai help chat user message)

  CHAT WITH FUNCTION
    --function MODULE:FUNCTION          (see: ai help chat function)

  CHAT WITH DATA                        (see: ai help chat with data)
    --index-name INDEX                  (see: ai help index name)
    --search-endpoint ENDPOINT          (see: ai help search endpoint)
    --search-api-key KEY                (see: ai help search key)

  OPTIONS                               (see: ai help chat options)
    --temperature TEMPERATURE           (see: ai help chat options temperature)
    --max-tokens MAX_TOKENS             (see: ai help chat options max-tokens)
    --top-p TOP_P                       (see: ai help chat options top-p)
    --n N                               (see: ai help chat options n)

EXAMPLES

  `EXAMPLE 1`: Bulk process inputs from JSONL file

    ai chat run --input-data questions.jsonl

  `EXAMPLE 2`: Bulk process inputs using an Azure Search index

    ai chat run --input-data questions.jsonl --index-name contoso_product_index

  `EXAMPLE 3`: Bulk process inputs using a python function

    ai chat run --input-data questions.jsonl --function copilot_aisdk:chat_completion 

SEE ALSO

  ai help chat
  ai help chat examples
  ai help find topics chat