TEST RUN

  The `ai test list` command runs CLI YAML tests.

USAGE: ai test run [...]

  FILES
    --file FILE
    --files FILE1 [FILE2 [...]]
    --files PATTERN1 [PATTERN2 [...]]

  TESTS
    --test TEXT
    --tests TEXT1 [TEXT2 [...]]

  FILTERING
    --contains TEXT1 [TEXT2 [...]]
    --remove TEXT1 [TEXT2 [...]]

EXAMPLES

  EXAMPLE 1: Runs all available tests

    ai test run

  EXAMPLE 2: Run tests from files under current directory, that contain 'setup' or 'nightly', and 'java', but not 'skip'

    ai test run --tests setup nightly --contains java --remove skip

  EXAMPLE 3: Run tests from files under 'tests' directory, that contain 'test3', but not 'skip'

    ai test run --files ../tests/**/*.yaml --contains test3 --remove skip

SEE ALSO

  ai help test examples
  ai help find topics test