parameters:
- name: telemetryType
  type: string
  default: None

variables:
- group: 'Azure AI CLI Telemetry configuration'
# NOTE: Do NOT update the names of the variables here without also updating the corresponding
# src\ai\.x\config\telemetry.config.json file. The variable names here need to be JPath like
# to replace specific values in that JSON configuration file. Please refer to the documentation
# for the FileTransform task for more details:
# https://learn.microsoft.com/azure/devops/pipelines/tasks/reference/file-transform-v1
- name: telemetry.type
  value: ${{ parameters.telemetryType }}
- name: telemetry.aria.tenantId
  value: $(AriaTenantId_Release)

steps:
- task: FileTransform@1
  displayName: 'Update telemetry configuration'
  inputs:
    folderPath: '$(Build.SourcesDirectory)/src/ai/.x/config'
    fileType: json
    targetFiles: telemetry.config.json
